### ISSUE TITLE
Add Tech Stack to `README.md`

### ISSUE THREAD

**Issue by gulsahsarsilmaz** [SamSverko/flatbread#1]
Create a Technology Stack to be chosen for both front and backend and discuss later.

**Comment by SamSverko** [comment]
**- Front end framework:** React
**- Data controller:** GraphQL (`apollo-server`)
**- Database:** MongoDB Atlas
**- Back end server:** AWS EC2
**- Static file hosting:** AWS S3
**- Domain & DNS:** AWS Route 53 (with Certificate Manager)
**- Distribution:** AWS CloudFront

How does this look @gulsahsarsilmaz ?

**Comment by gulsahsarsilmaz** [comment]
> **- Front end framework:** React
> **- Data controller:** GraphQL (`apollo-server`)
> **- Database:** MongoDB Atlas
> **- Back end server:** AWS EC2
> **- Static file hosting:** AWS S3
> **- Domain & DNS:** AWS Route 53 (with Certificate Manager)
> **- Distribution:** AWS CloudFront
> 
> How does this look @gulsahsarsilmaz ?

looks great!

**Comment by SamSverko** [comment]
What do you think @dwaldrum ?

**Comment by dwaldrum** [comment]
LGTM!
